# Generated by Django 5.0.6 on 2024-05-21 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('lastname', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('mobile', models.CharField(max_length=15, null=True)),
                ('gst', models.CharField(max_length=50, null=True)),
                ('tag', models.CharField(max_length=6, null=True)),
                ('dis', models.TextField(max_length=50, null=True)),
                ('category', models.TextField(max_length=254, null=True)),
                ('add', models.TextField(max_length=10, null=True)),
                ('city', models.CharField(max_length=10, null=True)),
                ('country', models.CharField(max_length=10, null=True)),
                ('pin', models.CharField(max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, upload_to='logo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Detail',
                'verbose_name_plural': 'Business Details',
            },
        ),
        migrations.CreateModel(
            name='Per_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('lastname', models.CharField(blank=True, max_length=50)),
                ('mobile', models.CharField(max_length=15, null=True)),
                ('city', models.TextField(max_length=50, null=True)),
                ('pin', models.TextField(max_length=6, null=True)),
                ('contry', models.TextField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('wmobile', models.CharField(max_length=10, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('married', models.CharField(max_length=10, null=True)),
                ('occupation', models.CharField(max_length=50, null=True)),
                ('profile', models.ImageField(blank=True, upload_to='profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Person Detail',
                'verbose_name_plural': 'Person Details',
            },
        ),
    ]
